### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by bulikos** [abipub/evm-proxy-detection#10]
Hello,
I have been looking into [test cases](https://github.com/gnosis/evm-proxy-detection/blob/main/test/detectProxyTarget.spec.ts) and found, that two cases are wrongly labeled and tests for some proxies are missing:

- `0x8260b9eC6d472a34AD081297794d7Cc00181360a` which is described as `detects EIP-897 delegate proxies`, but is EIP-1967-direct proxy case.
- `0xed7e6720Ac8525Ac1AEee710f08789D02cD87ecB` which is described as `detects OpenZeppelin proxies`, but is EIP-897 proxy case.

The first wrongly labeled test causes that the EIP-1967-direct is being tested twice. The second wrongly labeled one causes that OpenZeppelin proxy case is not tested at all. Same holds for EIP-1822 proxy (missing test).

**Comment by bulikos** [comment]
New finding. The `0x8260b9eC6d472a34AD081297794d7Cc00181360a` address implements the `implementation()` function (therefore its considered to be EIP-897 proxy) and also have occupied the EIP-1967 slot (therefore its considered to be EIP-1967 proxy). 

I believe, that the EIP-897 proxy should be detected only when the EIP-1967 slot is not used.

**Comment by mikhailxyz** [comment]
Thanks for reporting!

I'm not sure if either @jfschwarz or myself got time to maintain the package. It was solving an internal problem and covers all the needs - you are welcome to create a PR
